apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: {{ .Values.mysql_ns }}
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP