apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: {{ .Values.mysql_ns }}
spec:
  replicas: {{ .Values.phpmyadmin.replicaCount }}
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: {{ .Values.phpmyadmin.pmaHost }}
            - name: PMA_PORT
              value: {{ .Values.phpmyadmin.pmaPort }}
          ports:
            - containerPort: 80
      initContainers:
        - name: init-mysql-server
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql:3306; do echo waiting for mysql; sleep 2; done;']
      restartPolicy: Always
